### ISSUE TITLE
Problem in recognizing the device

### ISSUE THREAD

**Issue by sp8996** [topminipie/XiaoMiToolV2#15]
Login was successful but it couldnt detect the device. I ran "adb devices" separately it recognizes the device. But this tool can't. It shows this (in the screenshot below).
![Screenshot from 2024-01-01 22-27-11](https://github.com/topminipie/XiaoMiToolV2/assets/58138197/97d4beb0-d827-4c7a-9b82-f528a1c9496b)

**Comment by sp8996** [comment]
chmod +x res/tools/lin/adb fixed it

**Comment by topminipie** [comment]
Thank you, I'll put it in the instructions.
