### ISSUE TITLE
Unlock error

### ISSUE THREAD

**Issue by optimistixlab** [topminipie/XiaoMiToolV2#20]
Thank you for creating this fork, i Just tried this tool to unlock my xiaomi device, however it does not work :

![Screenshot at 2024-01-13 14-54-05](https://github.com/topminipie/XiaoMiToolV2/assets/13083485/8a882e7f-bfa5-479d-94c0-22870c1f8f70)

**Comment by topminipie** [comment]
Hi, try this [branch](https://github.com/topminipie/XiaoMiToolV2/tree/tested) and try use java 11 - https://adoptium.net/temurin/releases/

**Comment by topminipie** [comment]
It seems to be a problem with Xiaomi.
Try again in a few days.

**Comment by optimistixlab** [comment]
Thank you for the response, i have tried the tested version and use java 11 but it still does not work. I ended up using the official miunlock software on windows vm and it worked fine (need additional adb device driver installation in order the device can be recognized in fastboot mode)

**Comment by topminipie** [comment]
https://github.com/offici5l/MiTool/blob/main/MT/un-lock.py#L153C107-L153C210
