### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by flixcrls** [topminipie/XiaoMiToolV2#21]
Hi, thank you for developing the app, i want to ask, can macos for apple sillicon work?

**Comment by topminipie** [comment]
Hi.
I am not the developer of this application, it is a fork of the [original project](https://github.com/francescotescari/XiaoMiToolV2) with patches for correct bootloader unlocking.

I have no information if it works on macos (intel, Apple Silicon). I would be grateful for any information.

**Comment by flixcrls** [comment]
I mean thank you for continue the project cause this project is open source and abandon so long, thank you for your respond 🙌

**Comment by topminipie** [comment]
Fortunately there are alternatives to this project (regarding bootloader unlocking) - [Awesome Xiaomi BootLoader Unlock ](https://github.com/topminipie/awesome-xiaomi-bootloader-unlock)

**Comment by flixcrls** [comment]
sadly every tools can't run on macos apple sillicon, on past 6 months i try everything include virtubox, thats why im happy to hear this project running again by someone

**Comment by topminipie** [comment]
Perhaps these two projects will help you:
https://github.com/Canny1913/miunlock
https://github.com/offici5l/MiTool  (In tiori.)

**Comment by flixcrls** [comment]
I already try termux, in macos can't install termux, many say on reddit termux and mac terminal same but the command should be diff?, i read the issue canny1913 and recently many people failed to unlock 🤔
