### ISSUE TITLE
Can't log in to account

### ISSUE THREAD

**Issue by vi** [topminipie/XiaoMiToolV2#30]
First it offers confirm with the e-mail, after that it offers to add a recovery phone, but that also does not work.

Upstream version does log in successfully.

Workaroud:

1. Log in using the [usual version](https://github.com/francescotescari/XiaoMiToolV2/releases/download/v20.7.28/XMT2_Linux_20.7.28.run).
2. Copy `res/tmp/settings.app` into the fork's directory.
3. Start the fork. It would be pre-logged in.

Does not save from https://github.com/francescotescari/XiaoMiToolV2/issues/120 though.

**Comment by topminipie** [comment]
As far as I can remember, a cell phone is always required.

Apparently some dependency update broke it.
Use [tested version.](https://github.com/topminipie/XiaoMiToolV2/tree/tested)

*+* it's normal that the verification code doesn't come :)

**Comment by vi** [comment]
"tested" branch's (9ee136335ce0e1666fc75829056f6edfcbbd4e04) login also requests the verification code, then the phone number, then (after entering the number) a broken recaptcha screen on a black background with a "I'm not a robot" checkbox that cannot be checked.

**Comment by topminipie** [comment]
The original XiaoMiToolV2 doesn't have this?

**Comment by vi** [comment]
Tried running from commit a335da6bb812272d68d6842ff88c4b7552465cc4: login also broken, ending up with a broken captcha.

Tried running pre-built thing (https://github.com/francescotescari/XiaoMiToolV2/releases/download/v20.7.28/XMT2_Linux_20.7.28.run) again: login works instantly, without asking anything. Or at least it the closes the login window, reveals account id at the top of main window and saves `session_token` instantly.

Maybe something's with dependencies, not with the project code itself?

---

Attempt to run `com.xiaomitool.v2` classes built from source code, but everything else (other classes, Java interpreter, etc.) from the pre-built version is also not fruitful.

Maybe the code cannot properly reach into the embedded browser window, so never detects that login has happened?

**Comment by topminipie** [comment]
Right now I've assembled my XiaoMiToolV2 and logged into my account without a problem.

Update: Successfully logged into the account. (21.10.2024)
