### ISSUE TITLE
Can i use local rom or use mirror server, for bricked devices

### ISSUE THREAD

**Issue by jackestar** [topminipie/XiaoMiToolV2#60]
## Why

some servers are extremely slow ~50Kbit/s (same with several VPNs) and if I already have the official ROM or if I want to downgrade.
Also considering that the tool depends on said servers.

## A way

[src/main/java/com/xiaomitool/v2/xiaomi/miuithings/Mirrors.java](https://github.com/topminipie/XiaoMiToolV2/blob/12ecb0eac61246a533eadd71999f163a977b643e/src/main/java/com/xiaomitool/v2/xiaomi/miuithings/Mirrors.java#L13)

I see that in file Mirrors.java there is a function that would import them from a json, but instead it uses the value of `DEFAULT_MIRROR`.

I'm not very good with java btw, I don't know if I already directly make my json with the mirrors. And I don't want to have to recompile the project for each mirror

**Comment by topminipie** [comment]
This fork was created to maintain bootloader unlocking. Other features I do not recommend even trying to use. (they may not be up to date or compatible with HyperOS for example).
I advise you to manually download the image and install it or use other modern utilities (e.g. MiFlash Pro).
